name: ecoji
version: 1.0.0
summary: Ecoji encodes data as emojis.
description: |
  Ecoji encodes data as 1024 Unicode emojis.  The encoding supports concatenation.
  Encoded data sorts in the same order as the original data.

grade: stable
confinement: strict

parts:
  ecoji:
    source: .
    plugin: go
    go-importpath: github.com/keith-turner/ecoji

apps:
  ecoji:
    command: bin/ecoji
